import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { TRPCProvider } from "@/components/ui/trpc-provider";
import { cn } from "@/lib/utils";
import "./globals.css";
import Sidebar from "@/components/ui/sidebar";
import Header from "@/components/ui/header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Crispy | Fullstack Admin panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <TRPCProvider>
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <Sidebar />
            <div className="flex flex-col">
              <Header />
              {children}
            </div>
          </div>
        </TRPCProvider>
      </body>
    </html>
  );
}
